### ISSUE TITLE
Contribute to qutebrowser userscript

### ISSUE THREAD

**Issue by The-Compiler** [rsteube/qutebrowser-readability#1]
Just found this thanks to my google alert, sounds useful!

Any chance you want to open a PR to add the script to `misc/userscripts` [in the qutebrowser repo](https://github.com/The-Compiler/qutebrowser/tree/master/misc/userscripts)? That way it'll be automatically installed (at least on some distributions) and available via `:spawn -u readability` on any installation.

**Comment by rsteube** [comment]
Yes, wanted to do that anyway =)
